#!/usr/bin/env python3
"""Builds the Android launcher icon layers (vector drawables) from a character's JSON art.

Usage: python3 make_icon.py [expression-number]   (default 1)
Writes res/drawable/ic_launcher_foreground.xml and ic_launcher_monochrome.xml.
"""
import json, sys, pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent.parent
ART = ROOT / "WaterTracker" / "app" / "src" / "main" / "assets" / "art"
RES = ROOT / "WaterTracker" / "app" / "src" / "main" / "res" / "drawable"

# Outline bounds of the artwork (layer 0) and where it should sit inside the 108dp icon canvas.
def outline_bounds(art):
    from svgpathtools import parse_path  # dev-time only
    x0, x1, y0, y1 = parse_path(art["layers"][0]["d"]).bbox()
    return x0, y0, x1, y1

def argb(hex_color, alpha):
    r, g, b = hex_color[1:3], hex_color[3:5], hex_color[5:7]
    return "#%02X%s%s%s" % (max(0, min(255, round(alpha * 255))), r, g, b)

def build(art, monochrome):
    x0, y0, x1, y1 = outline_bounds(art)
    scale = 62.0 / (y1 - y0)                     # fit the height inside the icon's safe zone
    tx = 54.0 - (x0 + x1) / 2 * scale
    ty = 54.0 - (y0 + y1) / 2 * scale
    ink = art["layers"][0]["fill"]
    out = [
        '<?xml version="1.0" encoding="utf-8"?>',
        '<!-- Generated by v1/design/tools/make_icon.py from the character artwork. Do not edit by hand. -->',
        '<vector xmlns:android="http://schemas.android.com/apk/res/android"',
        '    xmlns:aapt="http://schemas.android.com/aapt"',
        '    android:width="108dp" android:height="108dp"',
        '    android:viewportWidth="108" android:viewportHeight="108">',
        f'    <group android:scaleX="{scale:.5f}" android:scaleY="{scale:.5f}" android:translateX="{tx:.3f}" android:translateY="{ty:.3f}">',
    ]
    for layer in art["layers"]:
        alpha = layer.get("alpha", 1.0)
        if monochrome:
            # Themed icons are tinted by shape alone, so keep only the dark linework and features.
            if layer["fill"] != ink:
                continue
            out.append(f'        <path android:fillColor="#FF000000" android:pathData="{layer["d"]}" />')
        elif layer["grad"]:
            g = layer["grad"]
            items = "".join(
                f'<item android:offset="{off}" android:color="{argb(col, a * alpha)}" />' for off, col, a in g["stops"]
            )
            if all(a * alpha < 0.03 for _, _, a in g["stops"]):
                continue
            out.append(
                f'        <path android:pathData="{layer["d"]}"><aapt:attr name="android:fillColor">'
                f'<gradient android:type="linear" android:startX="{g["x1"]}" android:startY="{g["y1"]}" '
                f'android:endX="{g["x2"]}" android:endY="{g["y2"]}">{items}</gradient></aapt:attr></path>'
            )
        else:
            if alpha < 0.03:
                continue
            out.append(f'        <path android:fillColor="{argb(layer["fill"], alpha)}" android:pathData="{layer["d"]}" />')
    out += ["    </group>", "</vector>", ""]
    return "\n".join(out)

if __name__ == "__main__":
    n = sys.argv[1] if len(sys.argv) > 1 else "1"
    art = json.loads((ART / f"expression-{n}.json").read_text())
    (RES / "ic_launcher_foreground.xml").write_text(build(art, monochrome=False))
    (RES / "ic_launcher_monochrome.xml").write_text(build(art, monochrome=True))
    print("wrote launcher icon layers from expression", n)
